### ISSUE TITLE
Cannot spawn fake players when using proxy protocol

### ISSUE THREAD

**Issue by Yetanotherwwzz** [sjavi4/PlayerDoll#64]
**Describe the bug**
Cannot spawn fake players when using proxy protocol

 - Paper 1.21
 - PlayerDoll 1.32
 - paper-1.21-106.jar
 
[21:11:10 INFO]: Nikkon447 issued server command: /doll spawn -player
[21:11:10 INFO]: [PlayerDoll] Wait for Login Listener
[21:11:10 INFO]: [PlayerDoll] Wait for Login Listener
[21:11:11 INFO]: [PlayerDoll] Wait for Login Listener
[21:11:11 INFO]: [PlayerDoll] Wait for Login Listener
[21:11:12 INFO]: [PlayerDoll] Wait for Login Listener
[21:11:12 INFO]: [PlayerDoll] Wait for Login Listener
[21:11:13 INFO]: [PlayerDoll] Wait for Login Listener
[21:11:13 INFO]: [PlayerDoll] Wait for Login Listener
[21:11:14 INFO]: [PlayerDoll] Wait for Login Listener
[21:11:14 INFO]: [PlayerDoll] Wait for Login Listener
[21:11:15 INFO]: [PlayerDoll] Client wait Too Long
[21:11:15 INFO]: [PlayerDoll] Client Connection Closed
[21:11:15 INFO]: [PlayerDoll] Connection Closed Successfully
[21:11:15 INFO]: [PlayerDoll] Client Thread End

**To Reproduce**
1. Set "proxy-protocol: true" in config/paper-global.yml and start the server
2. Execute "/doll spawn -player" in game
3. See error

**Expected behavior**
Fake player should be spawned normally

**Comment by sjavi4** [comment]
https://modrinth.com/plugin/playerdoll/version/1.33

A new config key `force-proxy-ip` is added. This should Fix the stated issue.

**Comment by Yetanotherwwzz** [comment]
> https://modrinth.com/plugin/playerdoll/version/1.33
> 
> A new config key `force-proxy-ip` is added. This should Fix the stated issue.

I turned on force-proxy-ip and set the right port. It still does not work.

```
[13:54:50 INFO]: Nikkon447 issued server command: /doll spawn 1
[13:54:50 INFO]: [PlayerDoll] Wait for Login Listener
[13:54:50 INFO]: [PlayerDoll] Wait for Login Listener
[13:54:51 INFO]: [PlayerDoll] Wait for Login Listener
[13:54:51 INFO]: [PlayerDoll] Wait for Login Listener
[13:54:52 INFO]: [PlayerDoll] Wait for Login Listener
[13:54:52 INFO]: [PlayerDoll] Wait for Login Listener
[13:54:53 INFO]: [PlayerDoll] Wait for Login Listener
[13:54:53 INFO]: [PlayerDoll] Wait for Login Listener
[13:54:54 INFO]: [PlayerDoll] Wait for Login Listener
[13:54:54 INFO]: [PlayerDoll] Wait for Login Listener
[13:54:55 INFO]: [PlayerDoll] Client wait Too Long
[13:54:55 INFO]: [PlayerDoll] Client Connection Closed
[13:54:55 INFO]: [PlayerDoll] Connection Closed Successfully
[13:54:55 INFO]: [PlayerDoll] Client Thread End
[13:54:55 INFO]: /127.0.0.1:44446 lost connection: Disconnected
```
